apiVersion: v1
kind: ConfigMap
metadata:
   name: orderdb-cm
data:
 host: orderdb-service
 database: order

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderdb
  labels:
    app: orderdb
spec:
  selector: 
    matchLabels:
      app: orderdb
  replicas: 1
  template:
    metadata:
      labels:
        app: orderdb
      name: orderdb-service

      
    spec:
      containers:
      - image: mongo:latest
        name: orderdb     
                
        ports:
        - containerPort: 27017
          name: orderdb 

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: orderdb
  name: orderdb-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: orderdb
  clusterIP: None