apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-app
  labels:
    app: order-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service-app
  template:
    metadata:
      labels:
        app: order-service-app
    spec:
      containers:
        - name: order-service-app
          image: raphaelfontys/order-service:master
          imagePullPolicy: Always
          ports:
            - containerPort: 9002
          env:
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: orderdb-cm
                  key: database
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: orderdb-cm
                  key: host

---

kind: Service
apiVersion: v1
metadata:
  name: order-service-svc
spec:
  selector:
    app: order-service-app
  ports:
    - port: 80
      targetPort: 9002