### Global
server:
  port: 9102
### End Global

### Kubernetes
spring:
  application:
    name: ORDER-SERVICE
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      host: '${MONGO_HOST:localhost}'
      port: 27017
      database: '${MONGO_DB:order}'

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

logging:
  level:
    root: DEBUG
### End Kubernetes

### Local
#spring:
#  application:
#    name: order-service
#  data:
#    mongodb:
#      host: mongo-orderdb
#      port: 27017
#      database: order
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-server:8761/eureka/
### End Local